_target_: src.models.classifier_module.MetClassLitModule

net:
  _target_: src.models.climate_classifier.ClimateClassifier
  encoder: ${paths.log_dir}/train/runs/2025-06-26_11-39-39/checkpoints/epoch_324.ckpt
  num_classes: 280
  output_dim: 512
  encoder_freeze: False

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler: null
#   _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
#   _partial_: true
#   mode: min
#   factor: 0.1
#   patience: 10

# compile model for faster training with pytorch 2.0
compile: false
